###
GET {{HostAddress}}/api/drivers
Accept: application/json

###
GET {{HostAddress}}/api/drivers/from-location?Latitude=5.662276533292582&Longitude=-0.20558562416544685&MaxRangeFromLocationInKm=3
Accept: application/json



