###
//driver requests
GET {{HostAddress}}/api/drivers

###
//specific driver
GET {{HostAddress}}/api/drivers/6da733c7-fcb2-4fab-804c-08dca2d8f5f8
Accept: application/json

###
//drivers from a location with a range
GET {{HostAddress}}/api/drivers/from-location?Latitude=5.662276533292582&Longitude=-0.20558562416544685&MaxRangeFromLocationInKm=3
Accept: application/json

###
//all drivers
GET {{HostAddress}}/api/Drivers?PageNum=1&PageSize=15
Accept: application/json

###
//all drivers
PUT {{HostAddress}}/api/Drivers/complete-trip/4C7276CB-E2FD-496F-3D19-08DCA44CBE08
Accept: application/json


###
//rider requests
//all riders
GET {{HostAddress}}/api/Riders?pageSize=3&pageNum=1

###
GET {{HostAddress}}/api/riders/active-trip/{id}

###
//specific rider
GET {{HostAddress}}/api/Riders/4257C77B-30CE-4B3D-FB08-08DCA2D8F5F0
Accept: application/json

###
//closest drivers
GET {{HostAddress}}/api/riders/closest-drivers?riderLocLatitude=5.662276533292582&riderLocLongitude=-0.20558562416544685&nClosestDrivers=5
Accept: application/json

###
POST {{HostAddress}}/api/Riders/request-ride
Content-Type: application/json
{
  "riderId": "139b566e-d553-4132-accc-08dca431ef4f",
  "currentLatitude": 5.693774885842252,
  "currentLongitude": -0.24502141829120092,
  "destinationLatitude": 5.662276533292582,
  "destinationLongitude": -0.20558562416544685
}

###
GET {{HostAddress}}/api/drivers/active-trip/{id}

###
//BackOffice related
GET {{HostAddress}}/api/BackOffice/trips?filter=All&pageSize=10&pageNum=1